displayName: MaxMind GeoIP2

summary: 'Getting data from MaxMind GeoIP databases and pass it downstream via HTTP request headers.'

type: middleware

import: github.com/thiagotognoli/traefikgeoip

testData:
  dbPath: 'GeoLite2-Country.mmdb'
  preferXForwardedForHeader: false
